version: "3.3"
services:
  web:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
     
     
    angular-service:
       container_name: ng-docker-example
       build: .
       ports:
           - "4200:80"
       
   
     
